<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DotaInsight.Application\DotaInsight.Application.csproj" />
      <ProjectReference Include="..\DotaInsight.Domain\DotaInsight.Domain.csproj" />
    </ItemGroup>

</Project>
